id: IDDA4C794
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T09:01:00+00:00'
last_modified: '2022-06-08T05:07:48.965992+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6346
  title: ཀྲུང་གོའི་བོད་རིག་པའི་དཔྱད་རྩོམ་བདམས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    FA54:
      image_group_id: I1KG8293
      title: ''
      total_pages: 1028
      order: 1
      base_file: FA54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
